# Generated by Django 5.1.3 on 2024-11-27 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decktracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decktracker.deck')),
            ],
        ),
        migrations.CreateModel(
            name='DeckModificationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decktracker.card')),
                ('deck_modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decktracker.deckmodification')),
            ],
        ),
    ]
