# Generated by Django 5.1.3 on 2024-11-27 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decktracker', '0002_deckmodification_deckmodificationcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckmodification',
            name='card',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='decktracker.card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deckmodification',
            name='quantity',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DeckModificationCard',
        ),
    ]
